import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ModalProvider } from "@/context/modal-auth";
import LoginModal from "@/components/modals/auth-modal";
import { Navbar } from "./(protected)/_components/navbar/navbar";
import { LocalAuthProvider } from "@/context/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  
        <LocalAuthProvider>
           <ModalProvider>
              <Navbar />
              {children}
            <LoginModal />
          </ModalProvider>
        </LocalAuthProvider>
        <Toaster
          position="top-center"
          toastOptions={{
            duration:2000,
            style: {
              background: '#333',
              color: '#fff',
            }
          }}
        />
      </body>
    </html>
  );
}
